server:
  port: 8070

spring:
  application:
    name: demo
# spring 로그를 컬러풀하게 설정 (무료 버전이신분)
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL # H2 DB 접속 주소: 프로젝트(실행 경로) 기준 ./db_dev 파일로 저장 + MySQL 문법 모드
    username: sa # DB 접속 계정명(H2 기본 계정이 보통 sa)
    password:
    driver-class-name: org.h2.Driver # 어떤 DB 드라이버를 쓸지 지정(H2 JDBC 드라이버)


#Sql 출력 관련 설정
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
    level:
      org.hibernate.orm.jdbc.bind: TRACE #trace하면 구체적으로 알려줌
      org.hibernate.orm.jdbc.extract: TRACE
